repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.1.1
  hooks:
   - id: nbqa-black
     additional_dependencies: ['black==19.10b0', 'nbconvert==5.6.1', 'nbdev==1.1.22', 'nbdime==1.1.0', 'nbqa==1.1.1','click==8.0.4']
     files: "nbs/.+"

