repos:
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.1.1
  hooks:
   - id: nbqa-black
     additional_dependencies: [black==21.7b0]
     files: "nbs/.+"
- repo: https://github.com/psf/black
  rev: 21.7b0
  hooks:
  - id: black
    files: "uberduck_ml_dev/.+"
